//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppItaqueraParaElas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DADOS_SEGURANCA
    {
        public string TIPO { get; set; }
        public string NOME { get; set; }
        public string ENDEREÇO { get; set; }
        public string BAIRRO { get; set; }
        public double LATITUDE { get; set; }
        public double LONGITUDE { get; set; }
        public long ID { get; set; }
        public string REGIAO { get; set; }
    }
}
